name: CI - Build Blazor WebAssembly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build do projeto Blazor WebAssembly
        run: dotnet build --configuration Release